name: BestProxy

on:
  push:
    branches:
      - main
    paths:
      - bestproxy.txt
  workflow_dispatch:

jobs:
  update_dns:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@main

    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.8

    - name: Test IP
      run: |
        wget https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.5/CloudflareST_linux_amd64.tar.gz
        tar xzf CloudflareST_linux_amd64.tar.gz
        ./CloudflareST -n 500 -sl 5 -tl 200 -tp 443 -tlr 0 -p 0 -dn 5 -f bestproxy.txt -url https://${{ secrets.TEST_URL }} -o result-443.txt
        awk -F "," 'NR==2 {print $1}' result-443.txt>ip.txt

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: BestProxy
      run: |
        python .github/workflows/bestproxy.py
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        CLOUDFLARE_BESTPROXY_NAME: ${{ secrets.CLOUDFLARE_BESTPROXY_NAME }}

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 5
